package seleniumDemo;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class demolaunch2 {
	public static void main(String[] args) {
		//to do Autogenerated method stub
		System.setProperty("webdriver.chrome.driver",".\\software\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://naukri.com/");
		System.out.println(driver.getTitle());
		//System.out.println(driver.getCurrentUrl());
		String parent =driver.get
		
	}

}
